# Generated by Django 4.0.2 on 2022-02-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('nome_cientifico', models.CharField(max_length=30)),
                ('descricao_curta', models.TextField(max_length=250)),
                ('descricao_longa', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/%Y/%m')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('preco', models.FloatField()),
            ],
        ),
    ]
